### ISSUE TITLE
Implement `!=` operator

### ISSUE THREAD

**Issue by fatmage** [fram-lang/dbl#108]
The `!=` operator is defined in https://github.com/fram-lang/dbl/blob/c17f2fb726c96c59daf25cbfc874f9fe36815eb8/lib/Prelude.dbl#L27 but it is not implemented in the lexer and parser yet.

![](https://i.ibb.co/ZM8hCyN/image.png)

**Comment by ppolesiuk** [comment]
It seems that the bug is in lexer/parser. Lexer correctly recognizes operators starting with `!`, and put them into class `OP_230` (is it a right name for such operator class?). The parser accepts such class only as unary operators with very high precedence (like `!` on OCaml). I see potential problem: should the expression `e1 !* e2` be parsed as binary operator or application of `e1` to unary operator expressions `!* e2`?
