### ISSUE TITLE
Awkward interaction of doc comments and single-line comments

### ISSUE THREAD

**Issue by forell** [fram-lang/dbl#166]
The convention for documentation comments that we agreed on a while back is something like follows.
```
{## A comment. #}
```
But, because `#` also starts single-line comments, if the closing `#}` is one the same line as the extra `#`, it won't get picked up by the lexer. This will also come up if we try to use markdown headers in comments.

**Comment by ppolesiuk** [comment]
I don't know if it is a bug, or feature. Block comments should interact with string and character literals. For instance `{# "#}" #}` should be considered as a valid comment. On the other hand, single-line comments ignore its contents, and ends with a new line (or end of file). I can imagine situations, where this feature of single-line comment can be useful in documentation comments, to write something that doesn't obey strict rules of block comment. If we write a documentation comment like this:
```
{## Some doc comment
  # more doc goes here
  # ### Markdown section in comment
  # ...
  #}
```
then the all contents is put in single-line comments, which could be nice.

As a solution, I can propose that single-line comments ended with `#}` could end block comments. However, this solution is still not perfect. Should the following comment be valid, or not?
```
{# {# # #} #}
```

Other simple solution, is to write documentation comments, that always ends in a separate line:
```
{## A comment.
#}
```

**Comment by ppolesiuk** [comment]
After the discussion with @forell we agreed that basically comments serve the two purposes:
- to document the code (documentation comments are the special case),
- to comment-out some code during prototyping.

For commenting-out code it is convenient to have some rules that implies that valid code can be always commented-out, e.g., supporting nested comments, ignoring comment terminators inside string literals, etc. In practice, these rules must be complicated, and lead to some counterintuitive behavior. For instance, in OCaml `(* '"' *)` is a valid comment, but `(* a'"' *)` is not valid. For documentation comments, we usually don't need such complicated rules, or even we would like to avoid them, because they may interact with documentation directives (see the first post in this discussion). However, the documentation can contain some code examples, which can contain other comments, so things start to be complicated. Moreover, we would like to have the language specification as simple as possible. For comparison, in C comments end with the first `*/` sequence, and it doesn't matter if it is inside another comment or string literal.

The solution that we propose, and that seems to satisfy all these requirements is to:
- disallow nested comments, and don't treat string literals specially (like in C),
- but to have many different parentheses for block comments.

To be more precise, block comments may start with `{#` followed by any (possibly empty) sequence *s* of characters from some set (e.g., `#`, operators, alphanumeric characters, `_`, `'`), and end with the first occurrence of same sequence *s* followed by `#}`. If commented-out code contains some comment, we can always find a comment name that doesn't appear there. For example:
```
{#aaa
{# this code is commented-out #}
let foo x = 42
aaa#}
```

Additionally, we can reserve comment names starting with `#` for documentation comments, for instance:
````
{## The documentation of foo ##}
let foo x = 42

{##bar The longer documentation of bar
A documentation can contain code examples:
```
{## with documentation comments ##}
let baz = bar
```
##bar}
let bar = ...
````
